In [10]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker('en_IN')
np.random.seed(42)

NUM_CUSTOMERS = 2000
NUM_TRANSACTIONS = 40000

cities = ["Pune", "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"]
merchant_categories = ["Electronics", "Grocery", "Travel", "Food", "Jewellery"]
device_types = ["Android", "iOS", "Web"]

# -------------------------
# Customers
# -------------------------
customers = []
for i in range(NUM_CUSTOMERS):
    customers.append({
        "customer_id": i,
        "city": random.choice(cities),
        "avg_spend": random.randint(500, 5000),
        "risk_segment": random.choice(["Low", "Medium", "High"])
    })

df_customers = pd.DataFrame(customers)

# -------------------------
# Devices
# -------------------------
devices = []
for i in range(NUM_CUSTOMERS):
    devices.append({
        "device_id": i,
        "device_type": random.choice(device_types),
        "is_trusted": random.choice([0,1])
    })

df_devices = pd.DataFrame(devices)

# -------------------------
# Transactions
# -------------------------
transactions = []
fraud_labels = []

for i in range(NUM_TRANSACTIONS):
    cust = df_customers.sample(1).iloc[0]
    
    amount = max(50, int(np.random.normal(cust["avg_spend"], 1000)))
    
    txn_time = fake.date_time_between(start_date="-30d", end_date="now")
    
    location = cust["city"]
    is_fraud = 0

    # --- Inject Fraud Patterns ---
    
    # Pattern 1: Night transactions
    if txn_time.hour >= 1 and txn_time.hour <= 5:
        if random.random() < 0.3:
            is_fraud = 1

    # Pattern 2: Location anomaly
    if random.random() < 0.1:
        location = random.choice([c for c in cities if c != cust["city"]])
        is_fraud = 1

    # Pattern 3: High amount spike
    if amount > cust["avg_spend"] * 3:
        if random.random() < 0.5:
            is_fraud = 1

    # Pattern 4: Untrusted device
    device = df_devices.sample(1).iloc[0]
    if device["is_trusted"] == 0 and random.random() < 0.4:
        is_fraud = 1

    transactions.append({
        "txn_id": i,
        "customer_id": cust["customer_id"],
        "amount": amount,
        "merchant_category": random.choice(merchant_categories),
        "txn_time": txn_time,
        "location": location,
        "device_id": device["device_id"]
    })

    fraud_labels.append({
        "txn_id": i,
        "is_fraud": is_fraud
    })

df_transactions = pd.DataFrame(transactions)
df_fraud = pd.DataFrame(fraud_labels)

# -------------------------
# Save CSVs
# -------------------------
df_customers.to_csv("customers.csv", index=False)
df_devices.to_csv("devices.csv", index=False)
df_transactions.to_csv("transactions.csv", index=False)
df_fraud.to_csv("fraud_labels.csv", index=False)

print("Dataset Generated Successfully!")

Dataset Generated Successfully!

In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\acer\anaconda3\lib\site-packages (9.6.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\acer\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [8]:
engine = create_engine(
    "mysql+pymysql://root:Vansh%401012@localhost:3306/fraud_detection"
)

In [9]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Vansh%401012@localhost:3306/fraud_detection")

print(engine.connect())

<sqlalchemy.engine.base.Connection object at 0x000001E038B86E90>

In [10]:
import pandas as pd

transactions = pd.read_sql("SELECT * FROM transactions", engine)
customers = pd.read_sql("SELECT * FROM customers", engine)
devices = pd.read_sql("SELECT * FROM devices", engine)
fraud = pd.read_sql("SELECT * FROM fraud_labels", engine)

In [11]:
print(transactions.shape)
print(transactions.head())

(40000, 7)
   txn_id  customer_id  amount merchant_category            txn_time location  \
0       0         1860    1080         Jewellery 2026-03-24 04:24:57  Chennai
1       1         1186    2873         Jewellery 2026-04-16 15:58:08  Chennai
2       2         1475    3316         Jewellery 2026-03-23 16:14:25    Delhi
3       3         1147      50           Grocery 2026-04-12 19:52:08  Chennai
4       4         1347      50              Food 2026-04-06 14:05:24    Delhi

   device_id
0       1487
1        302
2        417
3        208
4       1067

In [13]:
df = transactions.merge(customers, on="customer_id") \
                 .merge(devices, on="device_id") \
                 .merge(fraud, on="txn_id")

df.head()

,txn_id,customer_id,amount,merchant_category,txn_time,location,device_id,city,avg_spend,risk_segment,device_type,is_trusted,is_fraud
0,0,1860,1080,Jewellery,2026-03-24 04:24:57,Chennai,1487,Chennai,2375,Medium,Android,0,0
1,1,1186,2873,Jewellery,2026-04-16 15:58:08,Chennai,302,Chennai,1713,High,iOS,0,0
2,2,1475,3316,Jewellery,2026-03-23 16:14:25,Delhi,417,Delhi,4969,Medium,Android,0,0
3,3,1147,50,Grocery,2026-04-12 19:52:08,Chennai,208,Chennai,690,High,Web,0,0
4,4,1347,50,Food,2026-04-06 14:05:24,Delhi,1067,Delhi,1612,Low,Android,0,0

In [14]:
df["txn_time"] = pd.to_datetime(df["txn_time"])
df["txn_hour"] = df["txn_time"].dt.hour

In [17]:
# Spend Ratio
df["spend_ratio"] = df["amount"] / df["avg_spend"]

In [18]:
#Night Transaction
df["is_night"] = df["txn_hour"].apply(lambda x: 1 if 1 <= x <= 5 else 0)

In [19]:
#Location Anomaly

df["is_location_anomaly"] = (df["city"] != df["location"]).astype(int)

In [21]:
#Device Risk

df["is_untrusted_device"] = (df["is_trusted"] == 0).astype(int)

In [22]:
#Merchant Risk Score
merchant_risk = df.groupby("merchant_category")["is_fraud"].mean()

df["merchant_risk_score"] = df["merchant_category"].map(merchant_risk)

In [23]:
#Combo Feature

df["high_risk_combo"] = (
    df["is_night"] +
    df["is_location_anomaly"] +
    df["is_untrusted_device"]
)

In [24]:
#Check Features

df[[
    "spend_ratio",
    "is_night",
    "is_location_anomaly",
    "is_untrusted_device",
    "merchant_risk_score",
    "high_risk_combo"
]].head()

,spend_ratio,is_night,is_location_anomaly,is_untrusted_device,merchant_risk_score,high_risk_combo
0,0.454737,1,0,1,0.325558,2
1,1.677175,0,0,1,0.325558,1
2,0.667337,0,0,1,0.325558,1
3,0.072464,0,0,1,0.319773,1
4,0.031017,0,0,1,0.324378,1

In [25]:
# MODEL BUILDING 

# CELL 5: Define X and y

features = [
    "spend_ratio",
    "is_night",
    "is_location_anomaly",
    "is_untrusted_device",
    "merchant_risk_score",
    "high_risk_combo"
]

X = df[features]
y = df["is_fraud"]

In [27]:
# CELL 6: Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
# CELL 7: Train Model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [29]:
#RISK SCORING

# CELL 8: Generate Risk Score

df["risk_score"] = model.predict_proba(X)[:, 1]

In [30]:
# Check

df[["risk_score", "is_fraud"]].head()

   risk_score  is_fraud
0    0.694335         0
1    0.398995         0
2    0.351465         0
3    0.325933         0
4    0.323143         0

In [31]:
# STEP 6: DECISION ENGINE

#  Decision Function

def decision(score):
    if score > 0.8:
        return "DECLINE"
    elif score > 0.5:
        return "REVIEW"
    else:
        return "APPROVE"

In [32]:
# Apply Decision

df["decision"] = df["risk_score"].apply(decision)

In [33]:
# Output Check

df[["risk_score", "decision", "is_fraud"]].head()

   risk_score decision  is_fraud
0    0.694335   REVIEW         0
1    0.398995  APPROVE         0
2    0.351465  APPROVE         0
3    0.325933  APPROVE         0
4    0.323143  APPROVE         0

In [34]:
# Decision Distribution

df["decision"].value_counts()

decision
APPROVE    32285
DECLINE     3988
REVIEW      3727
Name: count, dtype: int64

In [35]:
# Fraud vs Decision

pd.crosstab(df["decision"], df["is_fraud"])

is_fraud      0     1
decision
APPROVE   25429  6856
DECLINE       7  3981
REVIEW     1589  2138

In [ ]:
# “I engineered behavioral features, built a risk scoring model, and implemented a rule-based decision engine to simulate real-time fraud control.”

In [36]:
# PHASE 7: EVALUATION

# STEP 1: Model Performance

from sklearn.metrics import confusion_matrix, classification_report

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5098  330]
 [1360 1212]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86      5428
           1       0.79      0.47      0.59      2572

    accuracy                           0.79      8000
   macro avg       0.79      0.71      0.72      8000
weighted avg       0.79      0.79      0.77      8000

In [37]:
# STEP 2: FALSE POSITIVE ANALYSIS

df["predicted"] = model.predict(X)

false_positives = df[(df["predicted"] == 1) & (df["is_fraud"] == 0)]

len(false_positives)

1596

In [38]:
# Understand them

false_positives[[
    "amount",
    "spend_ratio",
    "is_night",
    "is_location_anomaly",
    "is_untrusted_device"
]].head()

     amount  spend_ratio  is_night  is_location_anomaly  is_untrusted_device
0      1080     0.454737         1                    0                    1
36     4014     1.464964         1                    0                    1
67     1707     1.010657         1                    0                    1
93     3818     1.382832         1                    0                    1
118     528     0.403670         1                    0                    1

In [41]:
#STEP 3: THRESHOLD OPTIMIZATION

def decision_v2(score):
    if score > 0.9:
        return "DECLINE"
    elif score > 0.6:
        return "REVIEW"
    else:
        return "APPROVE"

df["decision_v2"] = df["risk_score"].apply(decision_v2)

In [42]:
# Compare

pd.crosstab(df["decision_v2"], df["is_fraud"])

is_fraud         0     1
decision_v2
APPROVE      25452  6889
DECLINE          0  3965
REVIEW        1573  2121

In [ ]:
# I optimized decision thresholds to balance fraud detection and customer experience, reducing false positives while maintaining detection efficiency.”

In [44]:
# STEP 4: BUSINESS METRICS

# Approval Rate

(df["decision"] == "APPROVE").mean()

np.float64(0.807125)

In [45]:
# Fraud Catch Rate

df[df["is_fraud"] == 1]["decision"].value_counts(normalize=True)

decision
APPROVE    0.528401
DECLINE    0.306821
REVIEW     0.164778
Name: proportion, dtype: float64

In [46]:
# False Positive Rate

false_positive_rate = len(false_positives) / len(df[df["is_fraud"] == 0])
false_positive_rate

0.05905642923219241

In [47]:
df.to_csv("final_fraud_dataset.csv", index=False)